name: higlass-scalable-insets
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python>=3.7
  - nodejs=10.*
  - jupyterlab
  - pandas
  - scipy
  - numpy
  - seaborn
  - matplotlib>=3.1
  - pip
